baseurl = "/"
googleAnalytics = ""
languageCode = "en-us"
theme = "stampfli"
title = "The Stämpfli Consortium"
[params]
description = "Your description"
favicon = "favicon.ico"
name = "Your name"
[params.about]
buttonText = "Get started!"
description = "We are a business-to-business service provider specialising in business, brand marketing and communications solutions. \n\nThe Stämpfli Consortium is essentially a group of consultants who have come together to work on brand marketing and business challenges. Whether you need 1 consultant, 2 or a full multi-skilled 360˚team, we can service you based on your specific needs. We can work at very competitive rates and flexible fees because of our set up and low overheads. \n\nStämpfli Consortium members possess significant expertise and experience, most with over 20 years, with a proven track-record of delivering results. By extension all members have a reputation based on excellence of quality work and professionalism. Singularly members are effective, synergistically we can do great things for you. \n\nThere is no task too big or too small for us."
headline = "A scalable business, marketing and communications SOLUTIONS provider"
[params.contact]
address = "8 Acton Court, Four Roads, Diego Martin, Trinidad"
description = "Give us a call or send us an email and we will get back to you as soon as possible!"
email = "rclstampfli@outlook.com"
headline = "Ready to start your next project with us?"
name = "Rachel Stämplfi"
phone = "868.684.9675"
title = "Founder & CEO"
[params.hero]
buttonText = "Find out more"
slogan = "<img src='img/sc_logo_main.png' alt=''>"
subtitle = "A network of independent, reputable, experienced and results-driven professionals. <br><br>Our purpose is to provide effective solutions to companies who want to move to their brands or commercial strength to the next level at palatable rates. We want to help you win!"
[params.mission]
description = "We do good stuff for you"
headline = "Our Mission"
[params.navigation]
brand = "The Stämpfli Consortium"
[params.navigation.links]
about = "About"
contact = "Contact"
portfolio = "Portfolio"
services = "Services"
[params.portfolio.modal]
buttonText = "Close"
category = "Category"
client = "Client"
date = "Date"
[params.services]
headline = "At your service"
[[params.services.list]]
description = "Brand Start-Ups, Refreshers ad, Re-Engineering, Marketing Plans and Roll-Out programmes, Market Research and Analysis"
icon = "fa-diamond"
title = "Branding and Marketing"
[[params.services.list]]
description = "Meetings, Conferences, Staff events, Activations and Award functions"
icon = "fa-calendar-check-o"
title = "Event Planning and Management"
[[params.services.list]]
description = "Website Design and Development, On-Line Strategy, Social Media Planning and Management, Content Creation, Other Digital Solutions"
icon = "fa-bullseye"
title = "Digital Marketing Strategy"
[[params.services.list]]
description = "Public Relations Strategy, Tactical Planning and Execution, PR for Specific Events or Campaigns, Crisis Communications Management, Media Relations and Management, Protocol Planning and Management"
icon = "fa-comments-o"
title = "PR and Corporate Communications"
[[params.services.list]]
description = "Revising Sales Strategy and Re-kitting your team, Sales Training, Lead generation and conversion, Creating or changing the sales culture in your organisation"
icon = "fa-line-chart"
title = "Sales-Force Strengthening"
[[params.services.list]]
description = "Quantitative and Qualitative, Economic Analyses and Reviews"
icon = "fa-book"
title = "Market Research and Analysis"
