baseurl = "/"
googleAnalytics = ""
languageCode = "en-us"
theme = "stampfli"
title = "The Stämpfli Consortium"
[params]
description = "Your description"
favicon = "favicon.ico"
name = "Your name"
[params.about]
buttonText = "Get started!"
description = "Founded by Rachel Stämpfli, a marketing and new business development professional with over 25 years’ experience. Rachel has worked with some of Trinidad’s leading FMCG brand distributors and manufacturers in the capacity of an Advertising Executive, a Media Marketing Manager, New Business Development Manager and most recently as the COO for the number #1 advertising agency in the English-speaking Caribbean.  Here are some of her career highlights,\n\n<h3>Life in the Advertising industry:</h3>\n\nWorked with 2 of Trinidad’s top advertising agencies, McCann Erickson and Lonsdale Saatchi & Saatchi. At McCann Erickson she managed a number of FMCG brands, local and International, such as, Maggi, , Johnson’s Baby, Stayfree, Neutrogena, Clean and Clear, Savlon, Splenda, “I Can’t Believe It’s Not Butter!”, Hellmann’s, Purex, Close-Up, Lux, Cadbury, SKYY, Riunite, Asti Riccadonna, Alpo, other Nestle Caribbean multi-brand initiatives and Lotus brand; non-FMCG accounts included, Standard Distributors and True Value Hardware.\n\nAs the Chief Operations Officer of Lonsdale Saatchi & Saatchi Advertising for over 7 ½ years she created, launched and co-managed 3 new business units within the agency - iuGO Digital; The Aesthetic 868-Events & Experiences and; Sage Corporate Communications & Publications. In doing so she also managed 360˚teams for special client projects where these BUs took the lead, such as,  the idea 2 innovation (i2i) entrepreneurship campaigns (5 consecutive programmes over 4 years) for The Ministry of Planning and Sustainable Development; various launches for Samsung mobile devices & Experience Stores; 3 Spirit of Sports of Awards (SOSA) events for The Sport Company of Trinidad & Tobago (sporTT), she also co -managed other events and conference for the Ministry of Planning and the Ministry of Community Development; and played a key role on the 2016 Scotiabank Foundation of Trinidad & Tobago for the 2016 Women Against Breast Cancer 5K event project, just to name a few.\n\nShe was the AMCHAM representative and the Saatchi Connector representative for Trinidad.\n\n<h3>Life in the Media sector:</h3>\n\nShe joined the media industry as the Marketing Manager of CCN TV6. Rachel then developed the business plan for the media group’s foray into the pageant world as the franchise holders of Miss Universe and Miss World for T&T, registered under the Trinidad & Tobago Pageant Company. She also a played an integral role in its kick-off as the head of marketing, sponsorship and sponsor relations.\n\nShe later co-founded and managed ReachCaribbean, the Caribbean’s first non-agency Pan-Caribbean media booking service. She has also sat on various committees such as the Programming Committee, Balanced Score Card T&T Roll-Out Team and was a representative for the Caribbean Communications Network (CCN) at the Trinidad & Tobago Publishers and Broadcasters Association (TTPBA).\n\n<h3>Life in the Non-Profit Organisation (NPO) sector:</h3>\n\nShe most recently held the position as Operations Manager of the T&T Chamber of Industry and Commerce responsible for the day-to-day operations of the Marketing, Communications, Membership Units.  She also co-managed Committee governance and initiatives alongside the CEO.  One of her primary roles was to transform and elevate the Champions of Business Awards events 2018, 2019 and 2020 with concept and theme development, communications, marketing and PR and other ideas to enhance sponsors, nominee and attendee experience. \n\nShe is also a past member of the Association of Female Executives of Trinidad & Tobago (AFETT) and a supporter of TTSPCA. \n\nOver 2 ½ decades has been spent building meaningful, working relationships across these various network groups. A number of these connections, some are considered to be “best in class” in their field,  have agreed to come together to form working groups when and as needed for projects.  This is the Stämpfli Consortium."
headline = "Who is the Stämpfli Consortium?"
[params.contact]
address = "8 Acton Court, Four Roads, Diego Martin, Trinidad"
description = "Give me a call or send me an email and I will get back to you as soon as possible!"
email = "rclstampfli@outlook.com"
headline = "Ready to start your next project with us?"
name = "Rachel Stämplfi"
phone = "868.684.9675"
title = "Founder & CEO"
[params.hero]
buttonText = "Find out more"
slogan = "<img class='main_logo' src='img/sc_logo_main.png' alt=''>"
subtitle = "A network of independent, reputable, experienced and results-driven professionals. <br><br>Our purpose is to provide effective solutions to companies who want to move to their brands or commercial strength to the next level at palatable rates. We want to help you win!"
[params.mission]
description = "• To inspire and guide companies on how to re-imagine their brands and companies to achieve new heights.\n\n• To create meaningful and rewarding opportunities for Consortium members and share holders to provide great work and service through synergy in a fair environment based on contribution.\n\n• To excite consumers with a renewed sense of connection to brands & companies."
headline = "Our Mission"
[params.navigation]
brand = "The Stämpfli Consortium"
[params.navigation.links]
about = "About"
contact = "Contact"
portfolio = "Portfolio"
services = "Services"
[params.portfolio.modal]
buttonText = "Close"
category = ["Category"]
client = "Client"
date = "Date"
[params.services]
headline = "At your service"
[[params.services.list]]
description = "Brand Start-Ups, Rebooting & Re-Engineering; Marketing Plan Development and Execution"
icon = "fa-diamond"
title = "Branding and Marketing"
[[params.services.list]]
description = "Meetings, Conferences, Staff Events, Activations, Award functions (virtual and in person) and other corporate events"
icon = "fa-calendar-check-o"
title = "Event Planning & Management"
[[params.services.list]]
description = "Website Design and Development, On-Line Strategy, Social Media Planning and Management, Content Creation, Other Digital Solutions"
icon = "fa-bullseye"
title = "Digital Marketing"
[[params.services.list]]
description = "Public Relations Strategy, Tactical Planning and Execution, PR for Specific Events or Campaigns, Crisis Management Communications, Media Relations and Management, Protocol Planning and Management"
icon = "fa-comments-o"
title = "PR and Corporate Communications"
[[params.services.list]]
description = "Revising Sales Strategy, Re-Kitting Sales Teams, Sales Team Organisation & Management, Sales Training, Lead Generation and Conversion, Creating /Changing the Sales Culture in Your Organisation"
icon = "fa-line-chart"
title = "Top Line / Sales-Force Strengthening"
[[params.services.list]]
description = "Quantitative and Qualitative, Economic Analyses and Reviews"
icon = "fa-book"
title = "Market Research and Analysis"
